plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.sinhgiang.wispra'
version = '1.0.0'

android {
  namespace "expo.modules.wispradictation"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
  testOptions {
    unitTests.returnDefaultValues = true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
